"""baseline schema

Revision ID: 20260602_000001
Revises: 
Create Date: 2026-06-02 12:21:50.433227+00:00
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel



revision: str = '20260602_000001'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasourceprovider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_configured', sa.Boolean(), nullable=False),
    sa.Column('credential_env_var', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('datasourceprovider', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_datasourceprovider_is_configured'), ['is_configured'], unique=False)
        batch_op.create_index(batch_op.f('ix_datasourceprovider_is_enabled'), ['is_enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_datasourceprovider_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_datasourceprovider_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_datasourceprovider_role'), ['role'], unique=False)

    op.create_table('instrument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('exchange', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('asset_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('instrument', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instrument_exchange'), ['exchange'], unique=False)
        batch_op.create_index(batch_op.f('ix_instrument_symbol'), ['symbol'], unique=False)

    op.create_table('operationlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operationlog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operationlog_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_operationlog_actor'), ['actor'], unique=False)

    op.create_table('paperrun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'succeeded', 'failed', name='taskstatus'), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('latest_equity', sa.Float(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paperrun', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paperrun_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_paperrun_strategy_id'), ['strategy_id'], unique=False)

    op.create_table('portfolio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_name'), ['name'], unique=False)

    op.create_table('strategyparameterset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('strategyparameterset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategyparameterset_strategy_id'), ['strategy_id'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('backtestrun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parameter_set_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'succeeded', 'failed', name='taskstatus'), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('result_payload', sa.JSON(), nullable=True),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parameter_set_id'], ['strategyparameterset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backtestrun', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backtestrun_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_backtestrun_strategy_id'), ['strategy_id'], unique=False)

    op.create_table('bar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('frequency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('adjust', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'frequency', 'timestamp', 'adjust', name='uq_bar_identity')
    )
    with op.batch_alter_table('bar', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bar_adjust'), ['adjust'], unique=False)
        batch_op.create_index(batch_op.f('ix_bar_frequency'), ['frequency'], unique=False)
        batch_op.create_index(batch_op.f('ix_bar_instrument_id'), ['instrument_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bar_timestamp'), ['timestamp'], unique=False)

    op.create_table('dataimporttask',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=True),
    sa.Column('frequency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('adjust', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'succeeded', 'failed', name='taskstatus'), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rows_imported', sa.Integer(), nullable=False),
    sa.Column('rows_updated', sa.Integer(), nullable=False),
    sa.Column('request_params', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dataimporttask', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataimporttask_adjust'), ['adjust'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataimporttask_frequency'), ['frequency'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataimporttask_instrument_id'), ['instrument_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataimporttask_status'), ['status'], unique=False)

    op.create_table('marketdataschedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('frequency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('end_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('adjust', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_status', sa.Enum('pending', 'running', 'succeeded', 'failed', name='taskstatus'), nullable=True),
    sa.Column('last_message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('marketdataschedule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_marketdataschedule_frequency'), ['frequency'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketdataschedule_instrument_id'), ['instrument_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketdataschedule_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketdataschedule_provider'), ['provider'], unique=False)

    op.create_table('portfolioinstrument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolioinstrument', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolioinstrument_instrument_id'), ['instrument_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolioinstrument_portfolio_id'), ['portfolio_id'], unique=False)

    op.create_table('publishedsnapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('backtest_run_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'revoked', name='snapshotstatus'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('immutable_payload', sa.JSON(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['backtest_run_id'], ['backtestrun.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('publishedsnapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publishedsnapshot_backtest_run_id'), ['backtest_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_publishedsnapshot_status'), ['status'], unique=False)

    op.create_table('sharelink',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['publishedsnapshot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sharelink', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sharelink_snapshot_id'), ['snapshot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sharelink_token_hash'), ['token_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sharelink', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sharelink_token_hash'))
        batch_op.drop_index(batch_op.f('ix_sharelink_snapshot_id'))

    op.drop_table('sharelink')
    with op.batch_alter_table('publishedsnapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publishedsnapshot_status'))
        batch_op.drop_index(batch_op.f('ix_publishedsnapshot_backtest_run_id'))

    op.drop_table('publishedsnapshot')
    with op.batch_alter_table('portfolioinstrument', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolioinstrument_portfolio_id'))
        batch_op.drop_index(batch_op.f('ix_portfolioinstrument_instrument_id'))

    op.drop_table('portfolioinstrument')
    with op.batch_alter_table('marketdataschedule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marketdataschedule_provider'))
        batch_op.drop_index(batch_op.f('ix_marketdataschedule_is_active'))
        batch_op.drop_index(batch_op.f('ix_marketdataschedule_instrument_id'))
        batch_op.drop_index(batch_op.f('ix_marketdataschedule_frequency'))

    op.drop_table('marketdataschedule')
    with op.batch_alter_table('dataimporttask', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataimporttask_status'))
        batch_op.drop_index(batch_op.f('ix_dataimporttask_instrument_id'))
        batch_op.drop_index(batch_op.f('ix_dataimporttask_frequency'))
        batch_op.drop_index(batch_op.f('ix_dataimporttask_adjust'))

    op.drop_table('dataimporttask')
    with op.batch_alter_table('bar', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bar_timestamp'))
        batch_op.drop_index(batch_op.f('ix_bar_instrument_id'))
        batch_op.drop_index(batch_op.f('ix_bar_frequency'))
        batch_op.drop_index(batch_op.f('ix_bar_adjust'))

    op.drop_table('bar')
    with op.batch_alter_table('backtestrun', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backtestrun_strategy_id'))
        batch_op.drop_index(batch_op.f('ix_backtestrun_status'))

    op.drop_table('backtestrun')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    with op.batch_alter_table('strategyparameterset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategyparameterset_strategy_id'))

    op.drop_table('strategyparameterset')
    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_name'))

    op.drop_table('portfolio')
    with op.batch_alter_table('paperrun', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paperrun_strategy_id'))
        batch_op.drop_index(batch_op.f('ix_paperrun_status'))

    op.drop_table('paperrun')
    with op.batch_alter_table('operationlog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operationlog_actor'))
        batch_op.drop_index(batch_op.f('ix_operationlog_action'))

    op.drop_table('operationlog')
    with op.batch_alter_table('instrument', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instrument_symbol'))
        batch_op.drop_index(batch_op.f('ix_instrument_exchange'))

    op.drop_table('instrument')
    with op.batch_alter_table('datasourceprovider', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_datasourceprovider_role'))
        batch_op.drop_index(batch_op.f('ix_datasourceprovider_priority'))
        batch_op.drop_index(batch_op.f('ix_datasourceprovider_name'))
        batch_op.drop_index(batch_op.f('ix_datasourceprovider_is_enabled'))
        batch_op.drop_index(batch_op.f('ix_datasourceprovider_is_configured'))

    op.drop_table('datasourceprovider')
    # ### end Alembic commands ###
